//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoanVienProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiDoan
    {
        public ChiDoan()
        {
            this.ChucVuChiDoans = new HashSet<ChucVuChiDoan>();
            this.DoanViens = new HashSet<DoanVien>();
        }
    
        public int MaChiDoan { get; set; }
        public string TenChiDoan { get; set; }
        public string TenVietTat { get; set; }
        public Nullable<int> MaDoanCoSo { get; set; }
        public Nullable<int> MaKhoaDaoTao { get; set; }
    
        public virtual DoanCoSo DoanCoSo { get; set; }
        public virtual KhoaDaoTao KhoaDaoTao { get; set; }
        public virtual ICollection<ChucVuChiDoan> ChucVuChiDoans { get; set; }
        public virtual ICollection<DoanVien> DoanViens { get; set; }
    }
}
