//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoanVienProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVu
    {
        public ChucVu()
        {
            this.ChucVuChiDoans = new HashSet<ChucVuChiDoan>();
            this.ChucVuDoanCoSoes = new HashSet<ChucVuDoanCoSo>();
        }
    
        public int MaChucVu { get; set; }
        public string ChucVu1 { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<ChucVuChiDoan> ChucVuChiDoans { get; set; }
        public virtual ICollection<ChucVuDoanCoSo> ChucVuDoanCoSoes { get; set; }
    }
}
