//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoanVienProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChucVuChiDoan
    {
        public string MaSinhVien { get; set; }
        public int MaChiDoan { get; set; }
        public int MaChucVu { get; set; }
        public Nullable<System.DateTime> NgayNhanChuc { get; set; }
    
        public virtual ChiDoan ChiDoan { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        public virtual DoanVien DoanVien { get; set; }
    }
}
