//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoanVienProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyChuyenSinhHoat
    {
        public int MaPhieuDangKy { get; set; }
        public string MaSinhVien { get; set; }
        public int MaSoChuyenSinhHoat { get; set; }
        public string LiDo { get; set; }
        public string TrangThai { get; set; }
        public System.DateTime NgayDangKy { get; set; }
    
        public virtual DoanVien DoanVien { get; set; }
        public virtual SoChuyenSinhHoat SoChuyenSinhHoat { get; set; }
    }
}
