//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoanVienProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanCoSo
    {
        public DoanCoSo()
        {
            this.ChiDoans = new HashSet<ChiDoan>();
            this.ChucVuDoanCoSoes = new HashSet<ChucVuDoanCoSo>();
        }
    
        public int MaDoanCoSo { get; set; }
        public string TenDoanCoSo { get; set; }
        public string TenDCSVietTat { get; set; }
    
        public virtual ICollection<ChiDoan> ChiDoans { get; set; }
        public virtual ICollection<ChucVuDoanCoSo> ChucVuDoanCoSoes { get; set; }
    }
}
