//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoanVienProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoatDong
    {
        public HoatDong()
        {
            this.DangKyHoatDongs = new HashSet<DangKyHoatDong>();
        }
    
        public int MaHoatDong { get; set; }
        public string TenHoatDong { get; set; }
        public Nullable<System.DateTime> ThoiGianBauDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<int> MaCapHoatDong { get; set; }
    
        public virtual CapHoatDong CapHoatDong { get; set; }
        public virtual ICollection<DangKyHoatDong> DangKyHoatDongs { get; set; }
    }
}
