//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoanVienProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanXet
    {
        public int NamNhanXet { get; set; }
        public string NoiDung { get; set; }
        public string XepLoai { get; set; }
        public Nullable<System.DateTime> NgayNhanXet { get; set; }
        public Nullable<int> MaSoDoan { get; set; }
    
        public virtual SoDoan SoDoan { get; set; }
    }
}
