//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoanVienProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDoanVienEntities : DbContext
    {
        public QuanLyDoanVienEntities()
            : base("name=QuanLyDoanVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<CapHoatDong> CapHoatDongs { get; set; }
        public DbSet<ChiDoan> ChiDoans { get; set; }
        public DbSet<ChucVu> ChucVus { get; set; }
        public DbSet<ChucVuChiDoan> ChucVuChiDoans { get; set; }
        public DbSet<ChucVuDoanCoSo> ChucVuDoanCoSoes { get; set; }
        public DbSet<DangKyChuyenSinhHoat> DangKyChuyenSinhHoats { get; set; }
        public DbSet<DangKyHoatDong> DangKyHoatDongs { get; set; }
        public DbSet<DoanCoSo> DoanCoSoes { get; set; }
        public DbSet<DoanVien> DoanViens { get; set; }
        public DbSet<DongDoanPhi> DongDoanPhis { get; set; }
        public DbSet<Grant> Grants { get; set; }
        public DbSet<HoatDong> HoatDongs { get; set; }
        public DbSet<KhenThuongKyLuatDoanVien> KhenThuongKyLuatDoanViens { get; set; }
        public DbSet<KhoaDaoTao> KhoaDaoTaos { get; set; }
        public DbSet<NhanXet> NhanXets { get; set; }
        public DbSet<SoChuyenSinhHoat> SoChuyenSinhHoats { get; set; }
        public DbSet<SoDoan> SoDoans { get; set; }
        public DbSet<SoDoanPhi> SoDoanPhis { get; set; }
        public DbSet<SoKhenThuongKyLuat> SoKhenThuongKyLuats { get; set; }
    }
}
