//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoanVienProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoChuyenSinhHoat
    {
        public SoChuyenSinhHoat()
        {
            this.DangKyChuyenSinhHoats = new HashSet<DangKyChuyenSinhHoat>();
        }
    
        public int MaSoChuyenSinhHoat { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
    
        public virtual ICollection<DangKyChuyenSinhHoat> DangKyChuyenSinhHoats { get; set; }
    }
}
