//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDoanVienProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoDoan
    {
        public SoDoan()
        {
            this.DoanViens = new HashSet<DoanVien>();
            this.NhanXets = new HashSet<NhanXet>();
        }
    
        public int MaSoDoan { get; set; }
        public string MaTheDoan { get; set; }
        public Nullable<System.DateTime> NgayVaoDoan { get; set; }
        public string NoiVaoDoan { get; set; }
        public Nullable<System.DateTime> NgayCapThe { get; set; }
        public string NoiCapThe { get; set; }
        public Nullable<System.DateTime> NgayNopSo { get; set; }
        public string TenSoDoan { get; set; }
    
        public virtual ICollection<DoanVien> DoanViens { get; set; }
        public virtual ICollection<NhanXet> NhanXets { get; set; }
    }
}
